name: Release RobIT Artifact

on:
  push:
    tags:
      - 'v*'  # Se ejecuta solo cuando haces push de un tag como v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          pytest --cov --cov-branch

      - name: Create artifact
        run: |
          mkdir robit_release
          cp -r main.py models README.md pyproject.toml robit_release/ || true
          zip -r RobIT-${{ github.ref_name }}.zip robit_release

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: RobIT-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
